FROM mdillon/postgis:9.6-alpine

ARG DB_CKAN_USER=ckan
ARG DB_CKAN_PASSWORD=ckan
ARG DB_CKAN_DB=ckan

ARG DB_DATASTORE=datastore
ARG DB_DATASTORE_RO_USER=datastore_ro
ARG DB_DATASTORE_RO_PASS=datastore

ENV POSTGRES_HOST_AUTH_METHOD=trust
ENV DB_CKAN_USER ${DB_CKAN_USER}
ENV DB_CKAN_PASSWORD ${DB_CKAN_PASSWORD}
ENV DB_CKAN_DB ${DB_CKAN_DB}

ENV DB_DATASTORE $DB_DATASTORE
ENV DB_DATASTORE_RO_USER $DB_DATASTORE_RO_USER
ENV DB_DATASTORE_RO_PASS $DB_DATASTORE_RO_PASS

COPY ./prepare_db.sh /docker-entrypoint-initdb.d

#VOLUME /var/lib/postgresql/data

ENTRYPOINT ["/docker-entrypoint.sh"]

EXPOSE 5432
CMD ["postgres"]
