# This Dockerfile is used to build a test image containing any test tools and
# scripts needed to test against our target container.
FROM postgres:9.5

RUN apt-get update && apt-get install -y netcat-traditional

ADD ./test.sh /usr/local/bin/test.sh

CMD ["test.sh"]
