#!/bin/bash
set -o errexit
set -o pipefail
set -o nounset

psql -U $POSTGRES_USER -c "CREATE USER ${DB_CKAN_USER} WITH PASSWORD '${DB_CKAN_PASSWORD}' SUPERUSER;" && \
psql -U $POSTGRES_USER -c "CREATE DATABASE ${DB_CKAN_DB} OWNER ${DB_CKAN_USER};" && \
psql -U $POSTGRES_USER -d $DB_CKAN_DB -c "CREATE EXTENSION postgis;"

psql -U $POSTGRES_USER -c "CREATE DATABASE ${DB_DATASTORE} OWNER ${DB_CKAN_USER};" && \
psql -U $POSTGRES_USER -c "CREATE ROLE ${DB_DATASTORE_RO_USER} NOSUPERUSER NOCREATEDB NOCREATEROLE LOGIN PASSWORD '${DB_DATASTORE_RO_PASS}';"