#!/bin/bash
set -e

psql -U $POSTGRES_USER -c "CREATE USER ${DB_CKAN_USER} WITH PASSWORD '${DB_CKAN_PASSWORD}' SUPERUSER;" && \
psql -U $POSTGRES_USER -c "CREATE DATABASE ${DB_CKAN_DB} OWNER ${DB_CKAN_USER};" && \
psql -U $POSTGRES_USER -c "CREATE DATABASE ${DB_PYCSW_DB} OWNER ${DB_CKAN_USER};" && \
psql -U $POSTGRES_USER -c "SELECT 1 FROM pg_database WHERE datname = '${DB_PYCSW_DB}';"